# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import requests
import yaml
from pathlib import Path


class Ui_LoginPage(object):
    def setupUi(self, LoginPage):
        LoginPage.setObjectName("LoginPage")
        LoginPage.resize(800, 600)
        LoginPage.setMinimumSize(QtCore.QSize(800, 600))
        LoginPage.setMaximumSize(QtCore.QSize(800, 600))
        LoginPage.setAutoFillBackground(True)
        self.centralwidget = QtWidgets.QWidget(LoginPage)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.label.setMaximumSize(QtCore.QSize(800, 600))
        self.label.setStyleSheet("background-color: rgb(0, 173, 239);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.textTitle = QtWidgets.QLabel(self.widget)
        self.textTitle.setGeometry(QtCore.QRect(330, 20, 131, 61))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.textTitle.setFont(font)
        self.textTitle.setStyleSheet("color: rgb(255, 255, 255);")
        self.textTitle.setObjectName("textTitle")
        self.textLogin = QtWidgets.QLabel(self.widget)
        self.textLogin.setGeometry(QtCore.QRect(260, 70, 291, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.textLogin.setFont(font)
        self.textLogin.setStyleSheet("color: rgb(255, 255, 255);")
        self.textLogin.setObjectName("textLogin")
        self.textLogin_2 = QtWidgets.QLabel(self.widget)
        self.textLogin_2.setGeometry(QtCore.QRect(40, 150, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.textLogin_2.setFont(font)
        self.textLogin_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.textLogin_2.setObjectName("textLogin_2")
        self.txtEmail = QtWidgets.QLineEdit(self.widget)
        self.txtEmail.setGeometry(QtCore.QRect(40, 210, 741, 51))
        self.txtEmail.setStyleSheet("background-color: rgb(0, 173, 239);\n"
                                    "border:none;\n"
                                    "border-bottom: 2px solid rgba(255,255,255,255);\n"
                                    "color:rgba(255,255,255,255);\n"
                                    "padding-bottom:7px;\n"
                                    "font-size:14px;")
        self.txtEmail.setObjectName("txtEmail")
        self.txtPassword = QtWidgets.QLineEdit(self.widget)
        self.txtPassword.setGeometry(QtCore.QRect(40, 340, 741, 51))
        self.txtPassword.setStyleSheet("background-color: rgb(0, 173, 239);\n"
                                       "border:none;\n"
                                       "border-bottom: 2px solid rgba(255,255,255,255);\n"
                                       "color:rgba(255,255,255,255);\n"
                                       "padding-bottom:7px;\n"
                                       "font-size:14px;")
        self.txtPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtPassword.setObjectName("txtPassword")
        self.textLogin_3 = QtWidgets.QLabel(self.widget)
        self.textLogin_3.setGeometry(QtCore.QRect(40, 280, 101, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.textLogin_3.setFont(font)
        self.textLogin_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.textLogin_3.setObjectName("textLogin_3")
        self.btnLogin = QtWidgets.QPushButton(self.widget)
        self.btnLogin.setGeometry(QtCore.QRect(600, 460, 131, 51))
        self.btnLogin.setStyleSheet("font-size:18px;\n"
                                    "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
                                    "border:none;\n"
                                    "color:white;\n"
                                    "font-weight:bold;\n"
                                    "border-radius:25px;\n"
                                    "")
        self.btnLogin.setObjectName("btnLogin")
        LoginPage.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(LoginPage)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        LoginPage.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(LoginPage)
        self.statusbar.setObjectName("statusbar")
        LoginPage.setStatusBar(self.statusbar)

        self.retranslateUi(LoginPage)
        QtCore.QMetaObject.connectSlotsByName(LoginPage)

        # for handle action button
        self.btnLogin.clicked.connect(self.loginAction)

    def retranslateUi(self, LoginPage):
        _translate = QtCore.QCoreApplication.translate
        LoginPage.setWindowTitle(_translate("LoginPage", "SIMAKET"))
        self.textTitle.setText(_translate("LoginPage", "SIMAKET"))
        self.textLogin.setText(_translate(
            "LoginPage", "Welcome to Login Page"))
        self.textLogin_2.setText(_translate("LoginPage", "Email"))
        self.textLogin_3.setText(_translate("LoginPage", "Password"))
        self.btnLogin.setText(_translate("LoginPage", "Login"))

    def loginAction(self):
        emails = self.txtEmail.text()
        passwords = self.txtPassword.text()

        if emails == '' and passwords == '':
            lin = QtWidgets.QMessageBox(self.centralwidget)
            lin.setText('Complete the form')
            lin.exec()
        else:
            hostlink = "https://marketing.pt-ckit.com/api/login_apps.php"
            datas = {'email': emails, 'password': passwords}

            try:
                resp = requests.post(hostlink, data=datas, timeout=None)
                retcode = resp.json()

                if(retcode['status'] == 'OK'):
                    with open(str(Path().absolute())+'/config/config.yaml', 'w') as f:
                        yaml.dump(retcode, f)
                    lin = QtWidgets.QMessageBox(self.centralwidget)
                    lin.setText('Login Success')
                    lin.exec()
                else:
                    lin = QtWidgets.QMessageBox(self.centralwidget)
                    lin.setText('Email/Password Incorrect')
                    lin.exec()

            except requests.ConnectionError as error:
                lines = QtWidgets.QMessageBox(self.MainWindow)
                lines.setText(error)
                lines.exec()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoginPage = QtWidgets.QMainWindow()
    ui = Ui_LoginPage()
    ui.setupUi(LoginPage)
    LoginPage.show()
    sys.exit(app.exec_())
