# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settingMenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SettingMenu(object):
    def setupUi(self, SettingMenu):
        SettingMenu.setObjectName("SettingMenu")
        SettingMenu.resize(800, 600)
        SettingMenu.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(SettingMenu)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.widget.setMaximumSize(QtCore.QSize(800, 600))
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.label.setMaximumSize(QtCore.QSize(800, 600))
        self.label.setStyleSheet("background-color: rgb(0, 173, 239);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("border:1px solid white;")
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.lblSubsribe = QtWidgets.QLabel(self.widget)
        self.lblSubsribe.setGeometry(QtCore.QRect(110, 80, 691, 31))
        self.lblSubsribe.setStyleSheet("font-size:14px;\n"
"font-weight:250;")
        self.lblSubsribe.setObjectName("lblSubsribe")
        self.lblNama = QtWidgets.QLabel(self.widget)
        self.lblNama.setGeometry(QtCore.QRect(110, 25, 691, 31))
        self.lblNama.setStyleSheet("font-size:14px;\n"
"font-weight:350;")
        self.lblNama.setObjectName("lblNama")
        self.btnBack = QtWidgets.QPushButton(self.widget)
        self.btnBack.setGeometry(QtCore.QRect(10, 140, 121, 31))
        self.btnBack.setObjectName("btnBack")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(20, 180, 771, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(20, 280, 771, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.txtMarkup = QtWidgets.QLineEdit(self.widget)
        self.txtMarkup.setGeometry(QtCore.QRect(20, 230, 671, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txtMarkup.setFont(font)
        self.txtMarkup.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.txtMarkup.setObjectName("txtMarkup")
        self.txtRemove = QtWidgets.QPlainTextEdit(self.widget)
        self.txtRemove.setGeometry(QtCore.QRect(20, 330, 671, 151))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txtRemove.setFont(font)
        self.txtRemove.setObjectName("txtRemove")
        self.btnSave = QtWidgets.QPushButton(self.widget)
        self.btnSave.setGeometry(QtCore.QRect(650, 500, 111, 41))
        self.btnSave.setStyleSheet("font-size:14px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border:none;\n"
"color:white;\n"
"font-weight:bold;\n"
"border-radius:20px;\n"
"")
        self.btnSave.setObjectName("btnSave")
        SettingMenu.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SettingMenu)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        SettingMenu.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SettingMenu)
        self.statusbar.setObjectName("statusbar")
        SettingMenu.setStatusBar(self.statusbar)

        self.retranslateUi(SettingMenu)
        QtCore.QMetaObject.connectSlotsByName(SettingMenu)

    def retranslateUi(self, SettingMenu):
        _translate = QtCore.QCoreApplication.translate
        SettingMenu.setWindowTitle(_translate("SettingMenu", "SIMAKET"))
        self.label_2.setText(_translate("SettingMenu", "ini Logo Nantinya"))
        self.lblSubsribe.setText(_translate("SettingMenu", "Anda berlangganan Aplikasi Ini mulai tanggal dd-mm-yyyy hingga dd-mm-yyyy"))
        self.lblNama.setText(_translate("SettingMenu", "Ini Nama Login User"))
        self.btnBack.setText(_translate("SettingMenu", "back to menu"))
        self.label_3.setText(_translate("SettingMenu", "Markup Percentage"))
        self.label_4.setText(_translate("SettingMenu", "Remove Text (separate by comma [,]) "))
        self.btnSave.setText(_translate("SettingMenu", "Save"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SettingMenu = QtWidgets.QMainWindow()
    ui = Ui_SettingMenu()
    ui.setupUi(SettingMenu)
    SettingMenu.show()
    sys.exit(app.exec_())
